### ISSUE TITLE
Server fails to start after update from 2.3.0 to 2.3.3

### ISSUE THREAD

**Issue by stevebread** [stormpath/express-stormpath#233]
Startup fails with the error

```
Error: API key ID and secret is required.
    at newError (d:\Dev\App\node_modules\express-stormpath\node_modules\stormpath\node_modules\stormpath-config\lib\strategy\ValidateClientConfigStrategy.js:15:14)
    at ValidateClientConfigStrategy.process (d:\Dev\App\node_modules\express-stormpath\node_modules\stormpath\node_modules\stormpath-config\lib\strategy\ValidateClientConfigStrategy.js:33:12)
    at fn (d:\Dev\App\node_modules\async\lib\async.js:741:34)
    at d:\Dev\App\node_modules\async\lib\async.js:1208:16
    at d:\Dev\App\node_modules\async\lib\async.js:166:37
    at d:\Dev\App\node_modules\async\lib\async.js:701:43
    at d:\Dev\App\node_modules\async\lib\async.js:167:37
    at Immediate._onImmediate (d:\Dev\App\node_modules\async\lib\async.js:1201:34)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
Stopping Express server
```

I noticed that `ValidateClientConfigStrategy.prototype.process` is called twice. The first time apiKey has the given id and secret, the second time apiKey is null causing the error.

**Comment by robertjd** [comment]
Hi Steve, thank you for the report.  Can you tell me how you're attempting to provide the API Key ID and Secret?  Is it through environment variables, or through a file (and if a file, where is is located?)

Thanks!

**Comment by stevebread** [comment]
Hey Robert,

The app was built based on the angular guide. In *app.js*
```
var app = express();
require('./components/stormpath').init(app);
var server = require('http').createServer(app);
require('./config/express')(app);
require('./routes')(app);
```

The `init` method of the stormpath module referenced above:
```
var config = require('../../config/environment');
exports.init = function(app) {
  applyPreRegistrationHandler(app);
  app.use(expressStormpath.init(app,{
    client: {
      apiKey: {
        id: config.stormpath.apiKeyId,
        secret: config.stormpath.apiKeySecret
      }
    },
    application: {
      href: config.stormpath.applicationHref
    },
    website: true,
    web: {
      spaRoot: path.join(config.root, app.get('env')==='production'?'public':'client', 'index.html')
    },
    postRegistrationHandler: postRegistrationHandler
  }));
};
```

The `config` module referenced above defined in *config\environment\development.js*
```
module.exports = {
  stormpath: {
    apiKeyId: process.env.STORMPATH_CLIENT_APIKEY_ID_X,
    apiKeySecret: process.env.STORMPATH_CLIENT_APIKEY_SECRET_X,
    applicationHref: process.env.STORMPATH_APPLICATION_HREF_X
  }
};
```

Environment variable definitions referenced above defined in *local.env.js*
```
module.exports = {
  STORMPATH_CLIENT_APIKEY_ID_X: '...',
  STORMPATH_CLIENT_APIKEY_SECRET_X: '...',
  STORMPATH_APPLICATION_HREF_X: '...',
};
```

**Comment by stevebread** [comment]
This seems to be related to the upgrade to `stormpath@0.15.1` and/or `stormpath-config@0.0.13`

The successful call to `ValidateClientConfigStrategy.prototype.process` results from the call to `expressStormpath.init` shown above.

The failed call results from this stack:
```
async.waterfall(), async.js:680
ConfigLoader.load(), ConfigLoader.js:54
anonymous(), Client.js:58
```
None of the strategies defined by ConfigLoader can locate the api key info.

**Comment by robertjd** [comment]
Hey Steve, yes the problem is that the version of stormpath-config that is depended on by express-stormpath is out of date.  We have our next release coming in a few days, and we'll get this updated then.  Thanks for helping us investigate!

**Comment by robertjd** [comment]
Hi @stevebread , this should be fixed in the new 2.3.4 release.  Can you give it a try?  Thanks!

**Comment by stevebread** [comment]
Works! Thanks @robertjd !

**Comment by typerandom** [comment]
Closing since issue is resolved.

**Comment by stevebread** [comment]
This issue is back. Did a clean install and found that startup fails. 2.3.4 pulls in deps stormpath@0.17.4  and stormpath-config@0.0.20. Reverted to stormpath@0.17.1  and stormpath-config@0.0.18 (the versions in my working environment) and the server starts.

**Comment by robertjd** [comment]
Hi @stevebread , thanks for the information.  Do you need to be on 2.3.4?  I'd suggest upgrading to 2.4.0, which has a lot of fixes regrading configuration parsing.

**Comment by stevebread** [comment]
Hi @robertjd , I'm sorry, typo in the previous comment. I meant to say 2.4.0 instead of 2.3.4. I need to downgrade the deps that 2.4.0 pulls in for it to work.

**Comment by robertjd** [comment]
Thanks @stevebread .  Can you tell me how you're trying to supply the api key information, e.g. environment variables or static files?   This will help us debug.

**Comment by stevebread** [comment]
Its an angular fullstack app. In *server/config/environment/production.js*
```
module.exports = {
  stormpath: {
    apiKeyId: stormpathCredentials.apiKeyId,
    apiKeySecret: stormpathCredentials.apiKeySecret,
    applicationHref: stormpathCredentials.applicationHref
  }
};
```
`stormpathCredentials` is part of a JSON config provided to the application.

The environment module is then used to initialize stormpath
```
var config = require('../../config/environment');
app.use(expressStormpath.init(app,{
  client: {
    apiKey: {
      id: config.stormpath.apiKeyId,
      secret: config.stormpath.apiKeySecret
    }
  },
  application: {
    href: config.stormpath.applicationHref
  },
  website: true,
  web: {
    spaRoot: path.join(config.root, app.get('env')==='production'?'public':'client', 'index.html')
  }
}));
```

**Comment by robertjd** [comment]
Thanks!  I can confirm the problem in 2.4.0, passing the API Key as you've shown does not work.

This problem does not exist in our latest 3.0 release that we made this week.  Would you be able to make an upgrade to that version? The [changelog is here](http://docs.stormpath.com/nodejs/express/latest/changelog.html#major-release-3-0-0) and the [upgrade guide is here](http://docs.stormpath.com/nodejs/express/latest/upgrading.html#version-2-4-0-version-3-0-0).  Please let me know if an upgrade is not possible, and we can try to find another solution.

**Comment by stevebread** [comment]
Since there are a lot of changes I won't be able to upgrade to 3.0 right away but no need for a fix on 2.4.0 because I haven't encountered a problem so far with the downgraded versions of the other libraries. If I do, I'll upgrade to 3.0 sooner :) Thanks @robertjd!

**Comment by robertjd** [comment]
Sounds good, happy to help!
